### ISSUE TITLE
Energy in block becomes negative (visually)

### ISSUE THREAD

**Issue by topbs** [HW9636/AutoSmithingTableMod#11]
When you connect energy to the block, it becomes a negative number. [The video](https://youtu.be/uzqPaPhOLC8) shows how it happens. BUT i still can craft, looks like its render bug. Also console spams message "**[Render thread/ERROR] [io.gi.hw.au.cl.AutoSmithingTableScreen/]: Argument 'toMap' is too big or too small (-31072 > 100000)**" Maybe the problem is in the modpack (FTB Stoneblock 3 1.2.3), but it seems to me that it is unlikely.

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2579
Issue reported on our tracker as well for dw20
