### ISSUE TITLE
[Request / Question] Backport to 1.16.5?

### ISSUE THREAD

**Issue by MundM2007** [HW9636/AutoSmithingTableMod#12]
Please backport to 1.16.5.
1.16.5 is still a great Version for Minecraft modding, because of the mod availability on that Version. Also it's great for modpack devs that want to plan ahead and work longer on a modpack (because 1.16.5 is mostly finished with available mods). So this would be a perfect Addition to that modlist.
Thanks!

**Comment by Gurkysword12** [comment]
yes it will get ported to 1.16.5 after 1.20 releases and we can release the rewrite for it then. After that 1.16 will be next.

**Comment by MundM2007** [comment]
Ok, thanks for your answer!
