### ISSUE TITLE
Crafts disappear in smithing table and auto smithing table for some mods when installed

### ISSUE THREAD

**Issue by batty80** [HW9636/AutoSmithingTableMod#4]
Awesome to have found a smithing table mod, I installed mod on 1.18.2 - FTB Direwolf20 1.9.1 modpack.
Once installed, multiple mod enabled crafts dissapeared from both Smithing Table and Auto Smithing Table (Verified not just missing from JEI). The missing mod related crafts include:
Advanced Netherite, Farmer's Delight, Supplimentaries, Create: Alloyed, Mythic Botany, Applied Energistics 2, Quark, FTB Industrial Contraptions
The following crafts still working include:
Base minecraft, Sophisticated Storage, Sophisticated Backpacks and Forbidden & Arcanus.

**Comment by benbenlaw** [comment]
can confirm that the recipe for the smithing table are not in JEI when this is installed. Recipes do still work though

**Comment by Gurkysword12** [comment]
Thanks for letting us know of this issue we'll try to fix it as fast as we can. Sorry for the late response.

**Comment by Gurkysword12** [comment]
Do the recipes that get removed something else then netherite?

**Comment by Gurkysword12** [comment]
Ok we have found the issue and were in the process of fixing it
